package com.github.okbuilds.okbuck

import com.github.okbuilds.core.dependency.DependencyCache
import com.github.okbuilds.core.system.BuildSystem
import com.github.okbuilds.core.task.OkBuildCleanTask
import com.github.okbuilds.core.util.InstallUtil
import com.github.okbuilds.core.util.RobolectricUtil
import com.github.okbuilds.okbuck.config.BUCKFile
import com.github.okbuilds.okbuck.generator.BuckFileGenerator
import com.github.okbuilds.okbuck.generator.DotBuckConfigLocalGenerator
import org.apache.commons.io.FileUtils
import org.apache.commons.io.IOUtils
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.logging.Logger

class OkBuckGradlePlugin implements Plugin<Project> {

    static final String OKBUCK = "okbuck"
    static final String OKBUCK_CLEAN = 'okbuckClean'
    static final String BUCK = "BUCK"
    static final String EXPERIMENTAL = "experimental"
    static final String INSTALL = "install"
    static final String INSTALL_BUCK = "installBuck"
    static final String DEFAULT_CACHE_PATH = ".okbuck/cache"

    static final String GROUP = "okbuck"

    static DependencyCache depCache
    static Logger LOGGER

    void apply(Project project) {
        LOGGER = project.logger
        OkBuckExtension okbuck = project.extensions.create(OKBUCK, OkBuckExtension, project)
        InstallExtension install = okbuck.extensions.create(INSTALL, InstallExtension, project)
        okbuck.extensions.create(EXPERIMENTAL, ExperimentalExtension)

        Task okBuckClean = project.tasks.create(OKBUCK_CLEAN, OkBuildCleanTask, {
            it.remove = okbuck.remove as Set<String>
            it.keep = okbuck.keep as Set<String>
        })

        okBuckClean.setGroup(GROUP)
        okBuckClean.setDescription("Delete configuration files generated by OkBuck")

        Task okBuck = project.task(OKBUCK)
        okBuck.setGroup(GROUP)
        okBuck.setDescription("Generate BUCK files")

        okBuck.outputs.upToDateWhen { false }
        okBuck.dependsOn(okBuckClean)
        okBuck << {
            generate(project)
        }

        Task installBuck = project.task(INSTALL_BUCK)
        installBuck.outputs.upToDateWhen { false }
        installBuck.setGroup(GROUP)
        installBuck.setDescription("Install buck")

        installBuck << {
            InstallUtil.install(project, BuildSystem.BUCK, install.gitUrl, install.sha, new File(install.dir))
        }

        project.afterEvaluate {
            ExperimentalExtension experimental = okbuck.experimental

            depCache = new DependencyCache(project, DEFAULT_CACHE_PATH, true, true, experimental.sources)

            if (experimental.robolectric) {
                Task fetchRobolectricRuntimeDeps = project.task('fetchRobolectricRuntimeDeps')
                okBuck.dependsOn(fetchRobolectricRuntimeDeps)
                fetchRobolectricRuntimeDeps.mustRunAfter(okBuckClean)
                fetchRobolectricRuntimeDeps.setDescription("Fetches runtime dependencies for robolectric")

                fetchRobolectricRuntimeDeps << {
                    RobolectricUtil.download(project)
                }
            }
        }
    }

    private static generate(Project project) {
        OkBuckExtension okbuck = project.okbuck

        // generate empty .buckconfig if it does not exist
        File dotBuckConfig = project.file(".buckconfig")
        if (!dotBuckConfig.exists()) {
            dotBuckConfig.createNewFile()
        }

        // generate .buckconfig.local
        File dotBuckConfigLocal = project.file(".buckconfig.local")
        PrintStream configPrinter = new PrintStream(dotBuckConfigLocal)
        DotBuckConfigLocalGenerator.generate(okbuck).print(configPrinter)
        IOUtils.closeQuietly(configPrinter)

        // generate BUCK file for each project
        Map<Project, BUCKFile> buckFiles = new BuckFileGenerator(project).generate()

        buckFiles.each { Project subProject, BUCKFile buckFile ->
            PrintStream buckPrinter = new PrintStream(subProject.file(BUCK))
            buckFile.print(buckPrinter)
            IOUtils.closeQuietly(buckPrinter)
        }
    }
}
